package com.tananaev.passportreader

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * §6.2 item 14 (D34/D37) pure-logic tests — no device/network required.
 *
 * The JWS vectors below (`GOOD_JWS`/`TAMPERED_JWS`/`WRONGKEY_JWS`/
 * `ALGNONE_JWS`/`WRONGKID_JWS`) were generated by an INDEPENDENT script
 * (`/tmp/.../scratchpad/gen-jws-vectors.mjs`, not committed) that imports
 * `spikes/m2-handoff/jws.mjs`'s `signJws` and
 * `spikes/m2-handoff/dev-request-signer-key.mjs`'s `DEV_REQUEST_SIGNER`
 * UNMODIFIED — this file only consumes the resulting compact-JWS strings,
 * mirroring the discipline `EvidenceSignerTest` uses for chiproof's known
 * vectors. If [RequestTrust] is ever edited in a way that breaks these,
 * re-run the generator against the spike's own signer — do not just update
 * the constants.
 */
class RequestTrustTest {

    private val devKey = RequestTrust.resolveVerifierKey("http://127.0.0.1:80")!!

    // Payload (decoded, for reference — not re-derived, just documents what
    // the vectors below assert about): response_uri=client_id=
    // http://127.0.0.1:4173/wallet/direct_post, state=req-abc123,
    // zkagent.tier=B, challenge.nonce=AAECAwQFBgcICQoLDA0ODw.
    private val GOOD_JWS =
        "eyJhbGciOiJFUzI1NiIsInR5cCI6Im9hdXRoLWF1dGh6LXJlcStqd3QiLCJraWQiOiJkZXYtcmVxdWVzdC1zaWduZXItMSJ9." +
            "eyJyZXNwb25zZV90eXBlIjoidnBfdG9rZW4iLCJyZXNwb25zZV9tb2RlIjoiZGlyZWN0X3Bvc3QiLCJjbGllbnRfaWQiOiJodHRwOi8vMTI3LjAuMC4xOjQxNzMvd2FsbGV0L2RpcmVjdF9wb3N0IiwiY2xpZW50X2lkX3NjaGVtZSI6InJlZGlyZWN0X3VyaSIsInJlc3BvbnNlX3VyaSI6Imh0dHA6Ly8xMjcuMC4wLjE6NDE3My93YWxsZXQvZGlyZWN0X3Bvc3QiLCJzdGF0ZSI6InJlcS1hYmMxMjMiLCJ6a2FnZW50Ijp7InNwZWMiOiJ6a2FnZW50LzEiLCJ0aWVyIjoiQiIsImV2aWRlbmNlX3JlcXVpcmVkIjpbInNpZy1wMjU2LzEiXSwiZXZpZGVuY2UiOltdLCJjaGFsbGVuZ2UiOnsibm9uY2UiOiJBQUVDQXdRRkJnY0lDUW9MREEwT0R3In19fQ." +
            "I8MlpM9O_kj3WaisspExTwHJh1M_4dzy6dPE5qYAYOpZ9PRCNIKV5Y0eFfqu25_m27IniDGQUgHVas_00UTiaA"

    // Same header/signature as GOOD_JWS, payload's zkagent.tier flipped B->A
    // after signing — must fail signature verification.
    private val TAMPERED_JWS =
        "eyJhbGciOiJFUzI1NiIsInR5cCI6Im9hdXRoLWF1dGh6LXJlcStqd3QiLCJraWQiOiJkZXYtcmVxdWVzdC1zaWduZXItMSJ9." +
            "eyJyZXNwb25zZV90eXBlIjoidnBfdG9rZW4iLCJyZXNwb25zZV9tb2RlIjoiZGlyZWN0X3Bvc3QiLCJjbGllbnRfaWQiOiJodHRwOi8vMTI3LjAuMC4xOjQxNzMvd2FsbGV0L2RpcmVjdF9wb3N0IiwiY2xpZW50X2lkX3NjaGVtZSI6InJlZGlyZWN0X3VyaSIsInJlc3BvbnNlX3VyaSI6Imh0dHA6Ly8xMjcuMC4wLjE6NDE3My93YWxsZXQvZGlyZWN0X3Bvc3QiLCJzdGF0ZSI6InJlcS1hYmMxMjMiLCJ6a2FnZW50Ijp7InNwZWMiOiJ6a2FnZW50LzEiLCJ0aWVyIjoiQSIsImV2aWRlbmNlX3JlcXVpcmVkIjpbInNpZy1wMjU2LzEiXSwiZXZpZGVuY2UiOltdLCJjaGFsbGVuZ2UiOnsibm9uY2UiOiJBQUVDQXdRRkJnY0lDUW9MREEwT0R3In19fQ." +
            "I8MlpM9O_kj3WaisspExTwHJh1M_4dzy6dPE5qYAYOpZ9PRCNIKV5Y0eFfqu25_m27IniDGQUgHVas_00UTiaA"

    // Same payload, signed by a FRESH, unrelated P-256 keypair (not the dev key).
    private val WRONGKEY_JWS =
        "eyJhbGciOiJFUzI1NiIsInR5cCI6Im9hdXRoLWF1dGh6LXJlcStqd3QiLCJraWQiOiJkZXYtcmVxdWVzdC1zaWduZXItMSJ9." +
            "eyJyZXNwb25zZV90eXBlIjoidnBfdG9rZW4iLCJyZXNwb25zZV9tb2RlIjoiZGlyZWN0X3Bvc3QiLCJjbGllbnRfaWQiOiJodHRwOi8vMTI3LjAuMC4xOjQxNzMvd2FsbGV0L2RpcmVjdF9wb3N0IiwiY2xpZW50X2lkX3NjaGVtZSI6InJlZGlyZWN0X3VyaSIsInJlc3BvbnNlX3VyaSI6Imh0dHA6Ly8xMjcuMC4wLjE6NDE3My93YWxsZXQvZGlyZWN0X3Bvc3QiLCJzdGF0ZSI6InJlcS1hYmMxMjMiLCJ6a2FnZW50Ijp7InNwZWMiOiJ6a2FnZW50LzEiLCJ0aWVyIjoiQiIsImV2aWRlbmNlX3JlcXVpcmVkIjpbInNpZy1wMjU2LzEiXSwiZXZpZGVuY2UiOltdLCJjaGFsbGVuZ2UiOnsibm9uY2UiOiJBQUVDQXdRRkJnY0lDUW9MREEwT0R3In19fQ." +
            "EJramoP44yb_Gdu__8PABx6wjQAMk8fIxACsfFAVEns0ISwaK72sbnoxzV05P85qjLP-UFiq19kin_7vcNP-IA"

    // Same payload, header alg=none (unsigned), empty signature segment.
    private val ALGNONE_JWS =
        "eyJhbGciOiJub25lIiwidHlwIjoib2F1dGgtYXV0aHotcmVxK2p3dCJ9." +
            "eyJyZXNwb25zZV90eXBlIjoidnBfdG9rZW4iLCJyZXNwb25zZV9tb2RlIjoiZGlyZWN0X3Bvc3QiLCJjbGllbnRfaWQiOiJodHRwOi8vMTI3LjAuMC4xOjQxNzMvd2FsbGV0L2RpcmVjdF9wb3N0IiwiY2xpZW50X2lkX3NjaGVtZSI6InJlZGlyZWN0X3VyaSIsInJlc3BvbnNlX3VyaSI6Imh0dHA6Ly8xMjcuMC4wLjE6NDE3My93YWxsZXQvZGlyZWN0X3Bvc3QiLCJzdGF0ZSI6InJlcS1hYmMxMjMiLCJ6a2FnZW50Ijp7InNwZWMiOiJ6a2FnZW50LzEiLCJ0aWVyIjoiQiIsImV2aWRlbmNlX3JlcXVpcmVkIjpbInNpZy1wMjU2LzEiXSwiZXZpZGVuY2UiOltdLCJjaGFsbGVuZ2UiOnsibm9uY2UiOiJBQUVDQXdRRkJnY0lDUW9MREEwT0R3In19fQ."

    // Same payload, signed BY the dev key (valid signature), but header kid
    // is "some-other-kid" instead of "dev-request-signer-1".
    private val WRONGKID_JWS =
        "eyJhbGciOiJFUzI1NiIsInR5cCI6Im9hdXRoLWF1dGh6LXJlcStqd3QiLCJraWQiOiJzb21lLW90aGVyLWtpZCJ9." +
            "eyJyZXNwb25zZV90eXBlIjoidnBfdG9rZW4iLCJyZXNwb25zZV9tb2RlIjoiZGlyZWN0X3Bvc3QiLCJjbGllbnRfaWQiOiJodHRwOi8vMTI3LjAuMC4xOjQxNzMvd2FsbGV0L2RpcmVjdF9wb3N0IiwiY2xpZW50X2lkX3NjaGVtZSI6InJlZGlyZWN0X3VyaSIsInJlc3BvbnNlX3VyaSI6Imh0dHA6Ly8xMjcuMC4wLjE6NDE3My93YWxsZXQvZGlyZWN0X3Bvc3QiLCJzdGF0ZSI6InJlcS1hYmMxMjMiLCJ6a2FnZW50Ijp7InNwZWMiOiJ6a2FnZW50LzEiLCJ0aWVyIjoiQiIsImV2aWRlbmNlX3JlcXVpcmVkIjpbInNpZy1wMjU2LzEiXSwiZXZpZGVuY2UiOltdLCJjaGFsbGVuZ2UiOnsibm9uY2UiOiJBQUVDQXdRRkJnY0lDUW9MREEwT0R3In19fQ." +
            "9a8YiFKlvZYyo3ZFfUEnoYM_RpDYFakPhmIGX4LY_XnQ6P9t64xYyt32uj7OuGkwpDy9XNU5uohM-t6D3I5lZQ"

    // ------------------------------------------------------- JWS verify

    @Test
    fun `positive - valid ES256 JWS from the pinned dev key verifies and decodes the payload`() {
        val result = RequestTrust.verifyRequestObject(GOOD_JWS, devKey)
        assertTrue("expected ok, got reason=${result.reason}", result.ok)
        assertNotNull(result.payload)
        assertEquals("B", result.payload!!.getJSONObject("zkagent").getString("tier"))
        assertEquals("http://127.0.0.1:4173/wallet/direct_post", result.payload.getString("response_uri"))
        assertEquals("req-abc123", result.payload.getString("state"))
    }

    @Test
    fun `negative - tampered payload fails signature verification`() {
        val result = RequestTrust.verifyRequestObject(TAMPERED_JWS, devKey)
        assertFalse(result.ok)
        assertNull(result.payload)
        assertEquals("signature_invalid", result.reason)
    }

    @Test
    fun `negative - signed by a wrong key fails signature verification`() {
        val result = RequestTrust.verifyRequestObject(WRONGKEY_JWS, devKey)
        assertFalse(result.ok)
        assertEquals("signature_invalid", result.reason)
    }

    @Test
    fun `negative - alg=none is refused, never trusted as unsigned`() {
        val result = RequestTrust.verifyRequestObject(ALGNONE_JWS, devKey)
        assertFalse(result.ok)
        assertNull(result.payload)
        assertTrue("expected an alg_mismatch reason, got ${result.reason}", result.reason?.startsWith("alg_mismatch") == true)
    }

    @Test
    fun `negative - valid signature but kid does not match the resolved key is refused`() {
        val result = RequestTrust.verifyRequestObject(WRONGKID_JWS, devKey)
        assertFalse(result.ok)
        assertTrue("expected a kid_mismatch reason, got ${result.reason}", result.reason?.startsWith("kid_mismatch") == true)
    }

    @Test
    fun `negative - plain JSON (not compact JWS) is refused`() {
        val result = RequestTrust.verifyRequestObject("""{"tier":"B"}""", devKey)
        assertFalse(result.ok)
        assertEquals("not_compact_jws", result.reason)
    }

    @Test
    fun `negative - malformed base64 segments never throw, always refuse`() {
        val result = RequestTrust.verifyRequestObject("not.valid.jws!!!", devKey)
        assertFalse(result.ok)
        assertNotNull(result.reason)
    }

    // ---------------------------------------------------- dev key resolution

    @Test
    fun `dev key is used for http 127-0-0-1, never for any other origin`() {
        val local = RequestTrust.resolveVerifierKey("http://127.0.0.1:4173")
        assertNotNull(local)
        assertTrue(local!!.isDev)
        assertEquals("dev-request-signer-1", local.kid)

        val localhost = RequestTrust.resolveVerifierKey("http://localhost:80")
        assertNotNull(localhost)
        assertTrue(localhost!!.isDev)

        // https on 127.0.0.1 is NOT the dev exception (D37: http-only, plain
        // loopback) — falls through to the well-known fetch, which fails
        // fast here (nothing listening) rather than ever silently reusing
        // the dev key for a scheme it isn't scoped to.
        val httpsLocal = RequestTrust.resolveVerifierKey("https://127.0.0.1:4173")
        assertNull(httpsLocal)
    }

    // -------------------------------------------------------------- origin

    @Test
    fun `origin match - same scheme host port, different paths`() {
        val a = RequestTrust.originOf("https://verifier.example/wallet/request.jwt/abc")
        val b = RequestTrust.originOf("https://verifier.example/wallet/direct_post")
        assertEquals(a, b)
        assertEquals("https://verifier.example:443", a)
    }

    @Test
    fun `origin mismatch - different port`() {
        val a = RequestTrust.originOf("https://verifier.example:8443/a")
        val b = RequestTrust.originOf("https://verifier.example/b")
        assertTrue(a != b)
    }

    @Test
    fun `origin mismatch - different scheme`() {
        val a = RequestTrust.originOf("http://verifier.example/a")
        val b = RequestTrust.originOf("https://verifier.example/a")
        assertTrue(a != b)
    }

    @Test
    fun `origin - explicit default port equals implicit default port`() {
        val explicit = RequestTrust.originOf("https://verifier.example:443/a")
        val implicit = RequestTrust.originOf("https://verifier.example/b")
        assertEquals(explicit, implicit)
    }

    @Test
    fun `origin - unparseable or schemeless input returns null`() {
        assertNull(RequestTrust.originOf("not a url"))
        assertNull(RequestTrust.originOf("/relative/path"))
    }

    // --------------------------------------------------- raw to DER signature

    @Test
    fun `rawToDer produces a well-formed SEQUENCE of two INTEGERs`() {
        val raw = ByteArray(64) { (it + 1).toByte() }
        val der = RequestTrust.rawToDer(raw)
        assertEquals(0x30, der[0].toInt() and 0xFF)
        // r's high byte (0x01) has no top bit set -> no padding needed there;
        // just sanity check total length is self-consistent (tag+len prefix
        // plus body), the real correctness check is GOOD_JWS verifying above.
        assertTrue(der.size > 64)
    }

    @Test(expected = IllegalArgumentException::class)
    fun `rawToDer rejects a signature that is not exactly 64 bytes`() {
        RequestTrust.rawToDer(ByteArray(63))
    }

    // -------------------------------------------------- tier parsing (item 13)

    private fun requestWithTier(tier: Any?): JSONObject {
        val zkagent = JSONObject()
        if (tier != null) zkagent.put("tier", tier)
        return JSONObject().put("zkagent", zkagent)
    }

    @Test
    fun `tierOf - A`() {
        assertEquals("A", RequestTrust.tierOf(requestWithTier("A")))
    }

    @Test
    fun `tierOf - B`() {
        assertEquals("B", RequestTrust.tierOf(requestWithTier("B")))
    }

    @Test
    fun `tierOf - C (well-formed, but item 13 leaves accepting it to the caller)`() {
        assertEquals("C", RequestTrust.tierOf(requestWithTier("C")))
    }

    @Test
    fun `tierOf - absent tier field returns null`() {
        assertNull(RequestTrust.tierOf(requestWithTier(null)))
    }

    @Test
    fun `tierOf - absent zkagent object entirely returns null`() {
        assertNull(RequestTrust.tierOf(JSONObject()))
    }

    @Test
    fun `tierOf - empty string tier returns null, not an empty tier`() {
        assertNull(RequestTrust.tierOf(requestWithTier("")))
    }

    @Test
    fun `tierOf - garbage tier value is returned as-is, validity is the caller's job`() {
        assertEquals("Z", RequestTrust.tierOf(requestWithTier("Z")))
        assertEquals("b", RequestTrust.tierOf(requestWithTier("b"))) // lowercase is NOT "B"
    }

    // ------------------------------------------- describeEvidenceRequired (D31)

    @Test
    fun `describeEvidenceRequired - absent zkagent object`() {
        assertEquals("absent", RequestTrust.describeEvidenceRequired(JSONObject()))
    }

    @Test
    fun `describeEvidenceRequired - absent evidence_required field`() {
        val requestObject = JSONObject().put("zkagent", JSONObject())
        assertEquals("absent", RequestTrust.describeEvidenceRequired(requestObject))
    }

    @Test
    fun `describeEvidenceRequired - empty array`() {
        val requestObject = JSONObject().put("zkagent", JSONObject().put("evidence_required", JSONArray()))
        assertEquals("absent", RequestTrust.describeEvidenceRequired(requestObject))
    }

    @Test
    fun `describeEvidenceRequired - D31 any-of group shape`() {
        val group = JSONArray(listOf("sig-ed25519/1", "sig-p256/1"))
        val requestObject = JSONObject().put("zkagent", JSONObject().put("evidence_required", JSONArray().put(group)))
        assertEquals("any-of[sig-ed25519/1,sig-p256/1]", RequestTrust.describeEvidenceRequired(requestObject))
    }

    @Test
    fun `describeEvidenceRequired - flat string list (older, pre-D31 shape) is passed through`() {
        val requestObject = JSONObject().put("zkagent", JSONObject().put("evidence_required", JSONArray(listOf("sig-ed25519/1"))))
        assertEquals("sig-ed25519/1", RequestTrust.describeEvidenceRequired(requestObject))
    }

    // ------------------------------------ expiresAtOf / isExpired (2026-09-01
    // real-device fix, "fix 3" — the consumed/expired handoff session)

    private fun requestWithExpiresAt(expiresAt: Any?): JSONObject {
        val challenge = JSONObject()
        if (expiresAt != null) challenge.put("expires_at", expiresAt)
        val zkagent = JSONObject().put("challenge", challenge)
        return JSONObject().put("zkagent", zkagent)
    }

    @Test
    fun `expiresAtOf - reads the challenge's expires_at epoch millis`() {
        assertEquals(1756767359000L, RequestTrust.expiresAtOf(requestWithExpiresAt(1756767359000L)))
    }

    @Test
    fun `expiresAtOf - absent expires_at field returns null`() {
        assertNull(RequestTrust.expiresAtOf(requestWithExpiresAt(null)))
    }

    @Test
    fun `expiresAtOf - absent challenge object returns null`() {
        val requestObject = JSONObject().put("zkagent", JSONObject())
        assertNull(RequestTrust.expiresAtOf(requestObject))
    }

    @Test
    fun `expiresAtOf - absent zkagent object entirely returns null`() {
        assertNull(RequestTrust.expiresAtOf(JSONObject()))
    }

    @Test
    fun `expiresAtOf - non-positive or non-numeric expires_at returns null, never a garbage value`() {
        assertNull(RequestTrust.expiresAtOf(requestWithExpiresAt(0L)))
        assertNull(RequestTrust.expiresAtOf(requestWithExpiresAt(-1L)))
        assertNull(RequestTrust.expiresAtOf(requestWithExpiresAt("not-a-number")))
    }

    @Test
    fun `isExpired - strictly after expiresAt is expired`() {
        assertTrue(RequestTrust.isExpired(expiresAtMillis = 1_000L, nowMillis = 1_001L))
    }

    @Test
    fun `isExpired - exactly at expiresAt is NOT expired, matching chiproof's own boundary`() {
        // packages/chiproof/src/challenge.js: `if (now > expiresAt) return realNo(...)`
        // — strict greater-than, so AT expiresAt the challenge is still valid.
        assertFalse(RequestTrust.isExpired(expiresAtMillis = 1_000L, nowMillis = 1_000L))
    }

    @Test
    fun `isExpired - before expiresAt is not expired`() {
        assertFalse(RequestTrust.isExpired(expiresAtMillis = 1_000L, nowMillis = 999L))
    }

    // ------------------------------------------------- thresholdOf (Q35 fix)

    private fun requestWithThreshold(threshold: Any?): JSONObject {
        val challenge = JSONObject()
        if (threshold != null) challenge.put("threshold", threshold)
        val zkagent = JSONObject().put("challenge", challenge)
        return JSONObject().put("zkagent", zkagent)
    }

    @Test
    fun `thresholdOf - reads a positive integer threshold`() {
        assertEquals(21, RequestTrust.thresholdOf(requestWithThreshold(21)))
    }

    @Test
    fun `thresholdOf - reads a different positive integer threshold`() {
        assertEquals(16, RequestTrust.thresholdOf(requestWithThreshold(16)))
    }

    @Test
    fun `thresholdOf - absent threshold field returns null`() {
        assertNull(RequestTrust.thresholdOf(requestWithThreshold(null)))
    }

    @Test
    fun `thresholdOf - absent challenge object returns null`() {
        val requestObject = JSONObject().put("zkagent", JSONObject())
        assertNull(RequestTrust.thresholdOf(requestObject))
    }

    @Test
    fun `thresholdOf - absent zkagent object entirely returns null`() {
        assertNull(RequestTrust.thresholdOf(JSONObject()))
    }

    @Test
    fun `thresholdOf - a quoted numeric string is rejected, never coerced`() {
        assertNull(RequestTrust.thresholdOf(requestWithThreshold("18")))
    }

    @Test
    fun `thresholdOf - a non-integer number is rejected`() {
        assertNull(RequestTrust.thresholdOf(requestWithThreshold(18.5)))
    }

    @Test
    fun `thresholdOf - zero is rejected, never treated as a valid threshold`() {
        assertNull(RequestTrust.thresholdOf(requestWithThreshold(0)))
    }

    @Test
    fun `thresholdOf - a negative threshold is rejected`() {
        assertNull(RequestTrust.thresholdOf(requestWithThreshold(-5)))
    }

    @Test
    fun `thresholdOf - a large in-range Long value round-trips correctly`() {
        assertEquals(1000, RequestTrust.thresholdOf(requestWithThreshold(1000L)))
    }
}
